apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: exam-nathansegers
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000:30001