apiVersion: v1
kind: Secret
metadata:
  name: regcredexamen
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvL2hvZG9taW5pYy90ZXN0LWltYWdlIjp7InVzZXJuYW1lIjoiZG9taW5pY2hvMDgwMSIsInBhc3N3b3JkIjoiIVBva2Vtb25ydWJ5MTIzIiwiZW1haWwiOiJkb21pbmljLmhvQHN0dWRiOiJkb21pbmljLmhvQHN0dWRlbnQuaG93ZXN0LmJlIiwiYXV0aCI6IlpHOXRhVzVwWTJodk1EZ3dNVG9oVUc5clpXMXZibkoxWW5reE1qTT0ifX19
type: kubernetes.io/dockerconfigjson